version: "3.7"
services:
    nginx:
        build: ./nginx
        image: cognitive:nginx
        container_name: cognitive_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./html/nginx:/var/www"
        networks:
            - cognitive-network
        depends_on:
            - node
    node:
        build: ./node
        image: cognitive:node
        container_name: cognitive_node
        restart: always
        networks:
            - cognitive-network
        depends_on:
            - postgres
        volumes:
            - "./html/node:/usr/src/cognitive-node/html"
            - "./node/src:/usr/src/cognitive-node/src"
    postgres:
        image: postgres:11.5-alpine
        container_name: cognitive_db
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - "./postgres:/var/lib/postgresql/data"
        networks:
            - cognitive-network
    adminer:
        image: adminer:latest
        container_name: cognitive_adminer
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        networks:
            - cognitive-network
networks:
    cognitive-network:
        driver: bridge
